"""Константы для Модели рецептов"""
TAG_NAME_MAX_LENGHT = 200
TAG_COLOR_MAX_LENGHT = 7
TAG_SLUG_MAX_LENGHT = 200
INGREDIENT_NAME_MAX_LENGHT = 200
INGREDIENT_MEASUREMENT_MAX_LENGHT = 200
RECIPE_NAME_MAX_LENGHT = 200
"""Константы для Представлений"""
USER_EMAIL_MAX_LENGHT = 254
USER_USERNAME_MAX_LENGHT = 150
USER_PASSWORD_MAX_LENGHT = 150
TAGS = 1
