"""Константы для Модели рецептов"""
TAG_NAME_MAX_LENGHT = 200
TAG_COLOR_MAX_LENGHT = 7
TAG_SLUG_MAX_LENGHT = 200
INGREDIENT_NAME_MAX_LENGHT = 200
INGREDIENT_MEASUREMENT_MAX_LENGHT = 200
RECIPE_NAME_MAX_LENGHT = 200
RECIPE_COOKING_TIME_MIN_VALIDATOR = 1
RECIPE_COOKING_TIME_MAX_VALIDATOR = 100
INGREDIENTRECIPE_AMOUNT_MIN_VALIDATOR = 1
INGREDIENTRECIPE_AMOUNT_MAX_VALIDATOR = 1000
"""Константы для Модели Пользователей"""
USER_EMAIL_MAX_LENGHT = 254
USER_PASSWORD_MAX_LENGHT = 150
USER_FIRST_NAME_MAX_LENGHT = 150
USER_LAST_NAME_MAX_LENGHT = 150
USER_USERNAME_MAX_LENGHT = 150
"""Константы для Проверки на дубликат."""
INTEGER_FOR_NOT_DUPLICATE = 1

